# -*- coding: utf-8 -*-
"""practical_exercise3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lGjEbw0CHmdSRjY0sMHf2L_Fj_CGZnY-

# Practical exercise 3:  Help Julia on her trip to New York

A friend of yours, Julia, goes to New York, US to visit her brother who is studying there. As soon as she lands at the JFK airport, she notices that the US is another world. The distance is measured in miles, mass is measured in pounds, and the temperature is measured in Fahrenheit. She is having trouble converting these values into metric units. Another problem is that she cannot remember the conversion ratios. Luckily, she has you as a friend. In this practical exercise, you will write a number of functions to help your friend in converting these values.

## Warm up

Your first task will be to write a greetings function for Julia so she can say hello to her brother Sam.

📌 Do you remember the greetings function? This function takes a name as an argument and returns "Hello" + name. 

Let's start with this function!
"""

def greetings(name):
  #Please write a greetings function
  return "Hello " + name

"""Now call this function to greet Sam!"""

#Call the greetings function to greet Sam
print(greetings("Sam"))

"""At the duty-free shops, Julia is comparing the prices of chocolates at different stores. She needs a difference calculator between two numbers. Can you create a function to calculate the difference for her?

📌 Similar to the example we saw in the lesson earlier, let's have a function that takes 2 numbers as an input and returns their difference.
"""

def difference(number1, number2):
  #Write a function that calculates the difference between two numbers
  return number1 - number2
print(difference(5, 3))

"""At one store the price of chocolate is 14.99 dollars and at another one it is 12.49 dollars. Let's call the difference function to compute the difference of those two prices."""

#Call the difference function to calculate the difference between the chocolate prices

def difference(num1, num2):
    return num1 - num2

price1 = 14.99
price2 = 12.49

print(difference(price1, price2))

"""## Julia is too lazy to introduce herself over and over again

In a new city, Julia will meet a lot of new people. To make her life easier, we can write a function for her so that she doesn’t have to do this over and over again… 

This function should include Julia's birthday, the place she was born and the place she currently lives. 

Julia has already defined 3 variables with her personal information.

"""

#Run this cell to store Julia's personal information in variables
birthday = "4 September 1996"
place_of_birth = "London"
current_city = "London"

"""Now, it's your turn to create a function *print_introduction* that takes these 3 arguments we defined above and print the following sentence:

"I was born on *birthday* in *place of birth* and now I live in *where she currently lives*."


"""

#Write an introduction function that takes birthday, place_of_birth and current_city as arguments
#and prints the sentence above
def print_introduction(birthday, place_of_birth, current_city):
    print("I was born on " + birthday + " in " + place_of_birth + " and now I live in " + current_city + ".")

"""Julia wants to introduce herself to a person she met at the airport. Let’s see if our program works:"""

#Call the introduction function 
print_introduction(birthday, place_of_birth, current_city)

"""While introducing herself, she noticed that from now on she has to change her current city! Can you help her by  creating a function that takes a new city name as an argument and changes the *current_city*?


📌 Remember that current_city is not in the scope of this function.
"""

#Write a function to change the current_city 

def change_city(new_city):
    global current_city
    current_city = new_city

"""So now, before introducing herself again, you help Julia change her current city to New York. Use the two functions above and print the introduction again."""

#Change current_city to "New York"


#Call the introduction function 

change_city("New York")
print(current_city) # Output: Berlin

"""#Julia needs a weather forecast

Julia finally left the airport and noticed that the weather is not as she expected. It's always good to know the weather forecast in the new city. 

You are provided with a 7 days' weather forecast. In the lesson, we discussed how you can construct a line plot using seaborn. Julia finds line plots confusing, try to create a bar plot for her to find out what the weather will be for the next 7 days. 

📌 Use the *barplot* method from the *seaborn* library with the data below.
"""

#We need to import the seaborn library
import seaborn as sns
import matplotlib.pyplot as plt
#Weather data 
day = [1, 2, 3, 4, 5, 6, 7]
avg_temperature = [14,9,3,11,18,27,6]

#Create a bar plot for the given data
sns.barplot(x=day, y=avg_temperature)
plt.xlabel("Day")
plt.ylabel("Avg. Temperature (°C)")
plt.title("7-Day Weather Forecast")
plt.show()

"""# Now let's define some functions for conversion

The reason Julia primarily contacted you was for some conversion functions. Now, we will define some functions that will help Julia to convert quantities.

We should start by importing the libraries that we might need during our implementation. Here we import the library math, but everyone has a different approach when it comes to coding. Keep in mind that depending on your technique, importing other libraries could be necessary. 
"""

# import library
import math

"""## Mile - Kilometer

Julia looked at the road sign and she sees that city center is 12 miles away from the airport. First, we will write a function for converting miles to kilometers. We know that **1 mile = 1.60934 kilometers**. We will use this information to write the function.

In this part, you will write 2 functions: 


1.   **mile2km**: this function will take mile as an argument and return equivalent kilometers.
2.   **km2mile**: this function will take km as an argument and return equivalent miles.



💣 Note: It is a naming convention to use '2' between the two quantities which indicates the conversion from the first quantity to the second quantity. 
"""

def mile2km(miles):
    kilometers = miles * 1.60934
    return kilometers

  #Write a function to convert miles to kilometers ü

def km2mile(km):
    miles = km / 1.60934
    return miles

# Output: 10 kilometers is equivalent to 6.21 miles.

  #Write a function to convert kilometers to miles

"""You can run this cell to test whether your program works or not:"""

### RUN THIS CELL TO TEST YOUR IMPLEMENTATION
assert math.isclose(mile2km(132.2), 212.754748, abs_tol=1e-5), "Test failed for mile2km!"
assert math.isclose(km2mile(48.44), 30.099295, abs_tol=1e-5), "Test failed for km2mile!"
print("Test passed!")

"""Now let’s convert the distance so that Julia actually understands it. Use the function mile2km() to convert 12 miles to equivalent kilometers."""

#Call the mile2km function to convert 12 miles
miles = 12
kilometers = mile2km(miles)
print("{} miles is equivalent to {:.2f} kilometers.".format(miles, kilometers))

"""## Pound - Kilogram

On her way, Julia got hungry and decided to buy some fruits. But she is confused by the weight units. She wants to buy 2 kilograms of apples for her brother. Therefore, she asked you to write a function that converts pounds to kilograms and kilograms to pounds. In this part, you will write only one function which is capable of converting pounds to kilograms and also from kilograms to pounds.

**1 pound =  0.45359 kilograms**

You will implement only one function. This function will return the converted quantity. There will be 2 arguments of this function:


1.   *quantity*: the magnitude of the measurement can either be an integer or a float. It can be pounds or kilograms.
2.   *mode*: this a string that indicates which conversion has to be computed. It can be either "pound2kg" or "kg2pound". 

📌 You can use if and else statements to implement this.

💣 Note: In the code we prepared, you can see the assert command. This command is there to make sure only valid arguments are passed. Here we can have if and else statements in the function and in any case where the mode is not pound2kg, the else block will be executed. Even if you accidentally have a typo in “pound2kg”. Therefore, it is important to make sure that the input arguments are valid.

💣💣 Tip: Always use assert command to ensure that your program runs without any errors. It is a common practice for Machine Learning engineers to ensure if the sizes of matrices are as expected. To use the assert command, write the keyword "assert" followed by a condition and then a string to indicate if the assertion has failed.

"""

def pound_kilogram(quantity, mode):
  assert mode == "pound2kg" or mode == "kg2pound", "Invalid argument!"
  #Here the assert command ensures that a valid mode is given as argument.
  
    #Write a statement to convert pound to kilogram for mode "pound2kg"
  if mode == "pound2kg":
      conversion_factor = 0.45359237
      result = quantity * conversion_factor
      return result

    #Else it should convert kilogram to pound
  else:
      conversion_factor = 2.20462
      result = quantity * conversion_factor
      return result

"""You can run this cell to test whether your program works or not:"""

### RUN THIS CELL TO TEST YOUR IMPLEMENTATION
assert math.isclose(pound_kilogram(2.20462, "pound2kg"), 1, abs_tol=1e-5), "Test failed for mode \"pound2kg\"!"
assert math.isclose(pound_kilogram(43, "kg2pound"), 94.79926, abs_tol=1e-5), "Test failed for mode \"kg2pound\"!"
print("Test passed!")

"""Julia wants to buy 2 kilograms of apples, so use the pound_kilogram() function to convert 2 kilograms to equivalent pounds."""

#Call the function to convert 2 kilograms to pound
print(pound_kilogram(2, "kg2pound"))

"""## Fahrenheit-Celsius

You might have noticed from the barplot above that the temperature in New York is unpredictable. And even worse for Julia, the temperatures are in Fahrenheit. In this part, you will write a function that will convert °C to °F and vice versa. The conversion formulas between these quantities are as follows:

**Formula: °C = (°F − 32) × 5/9** <br>
**Formula: °F = (°C x 9/5) + 32** 

You will implement only one function. This function will return the converted quantity. There will be 2 arguments of this function:



1.   *temperature*: the magnitude of the measurement can either be an integer or a float. It can be in Celsius or Fahrenheit.
2.   *mode*: this a string that indicates which conversion has to be computed. It can be either "f2c" or "c2f". 

📌 You can use if and else statements to implement this.


💣 Note: The assert command is there to make sure only valid arguments are passed.
"""

def fahrenheit_celcius(temperature, mode):
  assert mode == "f2c" or mode == "c2f", "Invalid argument!"
  # Write a statement to convert Fahrenheit to Celsius or Celsius to Fahrenheit

  if mode == "f2c":
    celsius = ((temperature - 32) * 5) / 9
    return celsius
  else:
    fahrenheit = (temperature * 9/5) + 32
    return fahrenheit

"""You can run this cell to test whether your program works or not:"""

### RUN THIS CELL TO TEST YOUR IMPLEMENTATION
assert math.isclose(fahrenheit_celcius(98.6, "f2c"), 37.0, abs_tol=1e-5), "Test failed for mode \"f2c\"!"
assert math.isclose(fahrenheit_celcius(42, "c2f"), 107.6, abs_tol=1e-5), "Test failed for mode \"c2f\"!"
print("Test passed!")

"""The temperature today is 88° Fahrenheit. Use the function defined above to convert it to equivalent °C."""

#Call the function to convert 88° Fahrenheit to Celsius
fahrenheit_celcius(88, "f2c")

"""This was a rough start for Julia, but thanks to your help she will survive her stay in New York! 😀"""