# -*- coding: utf-8 -*-
"""practical_exercise4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EzQc9s0XXd4ya1hvmoR8dmMudLAVAHH8

# Practical exercise 4: Your own supermarket

In this practical exercise, you are the owner of a supermarket.

🛒 You will program an online shop to sell different types of items. 

Please read the instructions carefully. There are hints and important explanations that will help you with this exercise.

##Warm up

Before we actually start, let's get a little more familiar with the data structures that will be useful in this exercise: lists, tuples and dictionaries. 

###(1) Lists

First, create a shopping list with items that you want to purchase from your online shop later. You need to buy: milk, apples, oranges, potatoes and bread.
"""

#Please create a shopping list
shopping = ['milk', 'apples', 'oranges', 'potatoes', 'bread']

print("Shopping List:", shopping)

"""You also want to buy bananas and onions, so you add those to your list.

Remember, there are two different ways to add an item to a list. 

📌 You can use the .append() method to add bananas to your list.

📌📌 You can use the .insert() method to add onions to your list. With this method you will also have to specify the position at which you want the item to be added.

💣 Make sure to print your shopping list afterwards to check if the items were added.
"""

#Use the append method to add bananas to your list
shopping.append('bananas')

#Print your shopping list
print("Shopping List:", shopping)

#Use insert method to add onions at a specific position in your list
shopping.insert(0, 'onions')

#Print your shopping list
print("Shopping List:", shopping)

"""Your roommate checks the shopping list and says that you already bought patatoes yesterday, so you decide to remove them from your list.

📌 You can use the .remove() method to remove an item from your list.
"""

#Use the remove method to remove potatoes from the list
shopping.remove('potatoes')
#Print your shopping list
print("Shopping List:", shopping)

"""###(2) Tuples
As a next step, lets make your list more informative, by adding the respective section in the store where you can find each item.

You can do this by using tuples, which contain the name of the item and the respective section. For example "fruits", "dairy", "bakery".

📌 Tuples are similar to lists, but you create them with round brackets, or parentheses ( ), instead of square ones [ ].

Your list should follow this structure:
```
shopping_list = [('item1', 'section1'), ('item2', 'section2')]
```


"""

#Expand your list by adding tuples for each item
shopping_list = [('milk', 'dairy'), ('apples', 'fruits'), ('oranges', 'fruits'), ('potatoes', 'vegetables'), ('bread', 'bakery')]

print("Shopping List:", shopping_list)

"""Next, you want to use this list to print out where each item is available. 

The message could be as follows: 
"You can find the [item] in the [section] section"


📌 You can use the for loop to pick each tuple at a time and unpack it inside the loop. 

📌📌 Finally, you can include the item and section variable in the print function.

"""

#Use for loop to iterate over list and get each tuple for unpacking
for item, section in shopping_list:

  #unpack the tuple into item and section variables 

  #print the message
    print(f"You cand find the {item} in the {section} section.")

"""###(3) Dictionaries

Another way to assign a section to each item is with dictionaries. Instead of a list containing multiple tuples, let's create a dictionary which contains the item as a key and the section as a value.

📌 Dictionaries are created with curly braces { } and each item in a dictionary consists of key/value pairs.

Your dictionary should follow this structure:
```
shopping_list = {'item1':'section1', 'item2':'section2'}
```


"""

#Create a dictionary which contains the item as key and the section as value
shopping_list_dict = {'milk': 'dairy', 'apples': 'fruits', 'oranges': 'fruits', 'potatoes': 'vegetables', 'bread': 'bakery'}

print("Shopping List:", shopping_list_dict)

"""We have learned different methods to access the items in a dictionary.

Let's use them first to print only the keys, then only the values and finally the key/value pairs as a list of tuples.

📌 You can use .keys() method to access the keys.

📌 You can use the .values() method to access the values.

📌 You can use the .items() method to access the key/value pairs.

"""

#Print the keys
print("Keys:", shopping_list_dict.keys())

#Print the values
print("Values:", shopping_list_dict.values())

#Print the key/value pairs
print("Key-Value Pairs:", shopping_list_dict.items())

"""# Set up the online shop

So, now that you have a gained some experience, let's start with our main exercise!

Of course, you first need to add all the items that will be available in your online shop. 

📌Create a dictionary for your inventory. For each item the key should be the name and the value should be a list containing price, stock, and section.

📌📌 Your dictionary should follow this structure: 
```
inventory = {'item1':[price, stock quantity,'section'], 'item2':[price, stock quantity,'section']}
```
💣 You can also write each item of the dictionary in its own line to make it more user-friendly:

```
inventory = {'item1':[price, stock quantity,'section'], 
             'item2':[price, stock quantity,'section']}
```
"""

#Create a dictionary for your inventory
inventory = {'milk': [2.50, 20, 'dairy'], 
            'apples': [0.99, 50, 'fruits'], 
            'oranges': [0.75, 30, 'fruits'], 
            'potatoes': [0.50, 40, 'vegetables'], 
            'bread': [2.00, 10, 'bakery']}

print("Inventory:", inventory)

"""# Your first client is here

Now that your inverntory is set up, your first client visits the shop. Let's take a peak in their shopping list.

📌 As we did in the warm up, let's create a shopping list for your first client with tuples for each item. This time, each tuple should consist of the item and the amount that they want to purchase.

The list should follow this structure:

```
shopping_list = [('item1', amount),('item2', amount)]
```


"""

#Create a shopping list that specifies how much of each item you want to purchase
shopping_list = [('milk', 2),('apples', 4),('oranges', 3),('potatoes', 5),('bread', 1)]

print("Shopping List:", shopping_list)

"""# What happens next? 

Everytime a customer wants to purchase something from your online shop, a few steps have to be taken. Here are the functions that will make your online shop work.

##(1) Check the stock
First, you have to make sure that you have sufficient stock of each item in your inventory. 

1. check_stock 

Define a function to check the stock quantity of the items in your shopping list. The function should take your shopping list and inventory as an argument. If there is not enough stock, the amount in your shopping list should be updated to the highest amount possible.


💣 To start, create an empty shopping list, in which the items and their updated amounts will be written in as tuples. Remember that we cannot update them because tuples are immutable.

📌 You can use a for loop to iterate over each item inside the shopping list.

📌 You can then unpack the tuples to access each item and amount separately.

📌 To access the available stock in your inventory dictionary, use the item as a key, then the corresponding index in the values list and check if there is enough stock. 

📌 The print function can help you to inform the client which items are out of stock and what the available amount is.

📌 Update the amount if necessary and append the item and amount to your updated shopping list.
"""

#Define the check_stock function
def check_stock(shopping_list, inventory):
  #Create the empty shopping_list_updated
  shopping_list_updated = []
  #Write a for loop to iterate over each item in your shopping list
  for item, amount in shopping_list:
    #Access the available stock in your inventory
    #append item and amount to your updated shopping list
    if item in inventory and inventory[item][1] >= amount:
      shopping_list_updated.append((item, amount))
    else:
      if item in inventory:
        print(f"Item: {item} is out of stock. Available amount: {inventory[item]}")
        shopping_list_updated.append((item, inventory[item]))
      else:
        print(f"Item: {item} is not available in our inventory")
  return shopping_list_updated

"""2. compute_bill

Next, we need to define a function to compute the bill and the price that has to be payed in the checkout. The function should take your **updated** shopping list and inventory as an argument.

💣 In the beginning of the function, you need to create a bill variable and assign 0 to it.

📌 You can use a for loop to iterate over each item inside the updated shopping list.

📌 You can then unpack the tuples to access each item and amount separately.

📌 To access the price in your inventory dictionary use the item as a key, then the corresponding index in the values list.

📌 Compute the price for the amount inside your client's updated shopping list and add it to your bill variable. 

"""

#Define the compute_bill function
def compute_bill(shopping_list, inventory):
  #Create a bill variable that equals 0
    bill = 0.0
  #Write a for loop to iterate over each item in your updated shopping list
    for item, amount in shopping_list:
    #access the price in your inventory
        price = inventory[item][0]
    #Compute the price and add it to the bill
        bill += price * amount
        print(price)
    return bill

"""3. update_stock

Your last function should update your store inventory after items were purchased. The function should take your **updated** shopping list and inventory as an argument.

📌 You can use a for loop to iterate over each item inside the updated shopping list.

📌 You can then unpack the tuples to access each item and amount separately.

📌 To access the stock in your inventory dictionary use the item as a key, then the corresponding index in the values list.

📌 Decrease the stock in your inventory by the amount that was purchased. 

"""

#Define the update_stock function 
def update_stock(shopping_list, inventory):
  #Write a for loop to iterate over each item in your updated shopping list
    for item, amount in shopping_list:
    #access the stock in your inventory
      stock = inventory[item][1]
    #Decrease the stock by the amount that was purchased
      inventory[item][1] = stock - amount
    return inventory

"""# Time to test if everything is working!

Now that you have your functions set up, you are ready to fulfil your client's shopping list.

1. Call the check_stock function

💣 The first thing that you need to do is to check whether there is enough stock available in your online shop. 

📌 Use the check_stock function to check if there is enough stock and if not, to update your shopping list accordingly.

📌 Next, print the following statement:

"Your updated shopping list is: [shopping_list]"
"""

#Call check_stock function for your shopping list
updated_shopping_list = check_stock(shopping_list, inventory)

print("Your updated shopping list is:", updated_shopping_list)

"""2.  Call the compute_bill function

Now you are sure that all items in your list are available, you need to compute how much you have to pay.

📌 Use the compute_bill function to find out how much you have to pay.

💣 Make sure that you give the **updated** shopping list as an argument!

📌 Next, print the following statement:
"Total price: [bill] $"
"""

#Call the compute_bill function for your updated shopping list
bill = compute_bill(updated_shopping_list, inventory)

print("Total price:", bill, "$")

"""3.   Call the update_stock function

Lastly, you have to make sure that your inventory gets updated after the purchase. 

📌 Use the update_stock function to update the inventory stock.

💣 Make sure that you give the **updated** shopping list as an argument!

📌 Next, print the following statement:
"The inventory has been updated: [inventory]"
"""

#Call the update_stock function for your updated shopping list
update_stock(updated_shopping_list, inventory)

print("The inventory has been updated:", inventory)