# -*- coding: utf-8 -*-
"""practical_exercise1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IPf7Yb_osajvG4M6yr1g2TnMrzMcGh41

# Practical exercise 1:  Plan an exciting adventure with a new friend

Welcome to your first practical exercise for this course. Here you will get a chance to practice the concepts we've covered in the video lessons from the module and apply your new coding skills to plan an exciting adventure with a new friend you meet online.

##Warm up

For this exercise, you will have to read the instructions, then write and run the code block. 

Let's test this. Do you remember all the keywords in Python? Probably not, but there is a quick and easy way to check them here.  

1. Write the help() function in the code cell below and run the code. 
2. In the prompt that appears, type "keywords" and they will pop up.
"""

help()

"""🧨 Is the code cell above still running? If so, you can't continue!

💣 Click the stop button next to the cell. Otherwise, it will continue to run infinitely and you will not be able to run other cells.

# Meet Amir

Let's say you are browsing the internet, when a pop up message shows on your screen, someone wants to meet you.
"""

#Run this cell to see the message
message = "Hello, my name is Amir! Nice to meet you. What is yours?"
print(message)

"""Now, how would you answer Amir? 

Use the cell below to prepare an answer for him with a greeting and your name and print it to the screen. 

📌 We use the built-in function print() in Python to show results as output.
"""

#Write your answer and print it on the screen
answer = "Hello there, I'm Doge, Doge the Developer"
print(answer)

"""Good job! Right away Amir writes you back with an intriguing question. He says, "Would you like to plan an exciting adventure with me today?" Well, why not! But before you start planning, maybe you need to learn a little bit more about each other.

#Get to know each other

You ask Amir to tell you a little bit about himself, and here's what he tells you.
"""

#Run the cell to see his message
his_age = 20
his_height = 1.76
his_hair_color = "brunette"
his_hometown = "Iran"
where_he_lives = "Turkey"

print("I am", str(his_age),"years old,",str(his_height),"tall",his_hair_color,"guy from",his_hometown,"but I currently live in",where_he_lives)

print("What about you? Tell me about yourself.")

"""Now it is your turn to share, but first some preparation is needed.

1. Write in information about yourself using the variables below. 
2. If there's something you don't want to share, you can use comments. Just put a "#" symbol in front of the code line and Python will not execute that line of code.
3. Check the datatype of each variable.

📌 Remember that there are different data types in Python and in order to use them in a sentence you may have to convert some of them. 
"""

#Please assign your age, height and other details you want to share.
age = 25
height = 0.25
hair = "yellow"
town = "Turkey"
live = "Turkey"

print("I'm", str(age), "years old.", str(height), "tall and I'm " ,str(hair),"and living in", str(live))
#Check the data type of the variables you want to use.

"""Great, now that you know what you want to share and which variables need to be converted to strings, you're ready to write your sentence. """

#Write a sentence using the print function to describe yourself using the variables above in the correct data type
print("I'm", str(age), "years old.", str(height), "tall and I'm " ,str(hair),"and living in", str(live))

"""#Where to go and what to eat

Now that you know each other a little better, you can start planning your adventure. But where do you start? 

Let's start with locations and food. Amir asks you to make a list of places in the world that you want to visit and meals that you like to eat.
 
Create a list 'favorite_places_and_foods' that contains at least 5 places and 5 meals.

"""

#Create your list
favorite_places_and_foods = ["1", "2", "3", "4", "5", "a", "b", "c", "d", "e"]

"""It's quite tough to choose from such great options. You need to narrow it down to three items per category. 

1. First you have to separate or 'slice' the places from the meals. 
2. Then select the first three items from the places list and the last ones from the foods list.
3. Print the remaining options to the screen. 

📌 Do you remember the list slicing technique? For example, Mylist[1:3] will give the second and third value from Mylist.
"""

#Create two separate lists for places and foods using the list slicing technique

places = favorite_places_and_foods[0:5]
print(places)
foods = favorite_places_and_foods[5:10]
print(foods)
#Select the first and last three from place and food lists


#Print both lists

"""It's quite hard to make a choice from these three. But why not let the computer choose for you? Do you remember the game of dice from our videos? Here is what you need to do.

1. Import the random module
2. Generate two random numbers between 0-2
3. Use each number as the index to choose an item from your favourite-place and food lists
4. Print the results to the screen

"""

#Please import the random module and generate two random numbers between 0 and 2
import random
list1 = [0, 1, 2]
roll = random.choice(list1)
print(roll)

#Use the generated numbers as indexes of randomely chosen items from place and food lists

choice = places[roll]
choice2 = foods[roll]
print(choice, choice2)

"""You must have found your location and food. But what else would you like to do on your adventure?

#Activities 

Now, you have your place and meals, but after lunch there are still lots of activities that you can do together...or separately.

Let's say there are three pre-defined options: playing chess, playing tennis and visiting a museum. Chess and tennis require both of you to participate, but you can visit the museum separately as well. 

We need a code to indicate which activities each of you would like to do and which ones will be able to do. A chance to use our logical operators. 

1. Define activities
2. Use the operands 'True' and 'False' to indicate your and Amir's preference for each activity
3. Use the logical operators 'and' and 'or' to define which activities you will be able to do

📌 Please add in the responces for Amir as well, by the way he doesn't like sports, but loves board games.
"""

first_activity = "lets play chess in the park"
second_activity = "lets play a game of tennis"
third_activity = "lets go to the museum"

#Write your and Amir's preference for each activity either as "True" or "False"

#First activity
first_activity_your = "playing video games"
first_activity_friend = first_activity

#Example statement
print("We are going to play chess in the park! Answer:" ,first_activity_your and first_activity_friend)
 
#Second activity
second_activity_your = "running"
second_activity_friend = second_activity
 
#Your turn to write the statement


#Third activity

#Your turn to write the statement

"""#Get a date

Finally you know where to meet, what to eat and what do to. The only last thing to decide is when to meet. How would you ask Amir for the date and time he wants to go on this adventure with you? 

📌📌Hint: Use the input() function.
"""

#Create a variable for your trip date that asks Amir for an input

print("Enter date")
x = str(input())
print("date=" + x)
#Print the date for the trip by using it in a sentence
name = "Deniz"
a = 3
type (name * a)